from __future__ import annotations

import json
from pathlib import Path


def _safe_name(name: str) -> str:
    cleaned = "".join(c if c.isalnum() or c in "-_" else "-" for c in name.strip())
    return cleaned.strip("-") or "mcp-server"


def generate_server(name: str, out: Path, tools: int = 2) -> Path:
    """Create a secure-by-default MCP server scaffold."""
    safe = _safe_name(name)
    pkg = safe.replace("-", "_")
    root = out / safe
    tools = max(1, min(tools, 20))

    (root / "src" / pkg / "tools").mkdir(parents=True, exist_ok=True)
    (root / "tests").mkdir(parents=True, exist_ok=True)
    (root / "schemas").mkdir(parents=True, exist_ok=True)
    (root / ".github" / "workflows").mkdir(parents=True, exist_ok=True)

    # pyproject
    (root / "pyproject.toml").write_text(
        f"""[project]
name = "{safe}"
version = "0.1.0"
description = "MCP server generated by x4-mcpgen (secure defaults)"
requires-python = ">=3.11"
license = {{ text = "Apache-2.0" }}
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=8.0", "ruff>=0.6"]

[project.scripts]
{safe} = "{pkg}.server:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
""",
        encoding="utf-8",
    )

    # README
    (root / "README.md").write_text(
        f"""# {safe}

MCP server generated by [x4-mcpgen](https://github.com/dhe-cruzer69/x4-mcpgen).

## Quick start

```bash
pip install -e ".[dev]"
pytest -q
python -m {pkg}.server --help
```

## Security defaults

- Explicit tool list (no wildcards)
- stdio transport only
- Non-root Docker user
- Run `x4-sec scan .` before deploy

## License

Apache-2.0
""",
        encoding="utf-8",
    )

    # package init + server
    (root / "src" / pkg / "__init__.py").write_text('__version__ = "0.1.0"\n', encoding="utf-8")

    tool_imports = "\n".join(
        f"from .{pkg}.tools.tool_{i} import run as tool_{i}_run" for i in range(1, tools + 1)
    )
    # fix relative import path in generated server
    tool_imports = "\n".join(
        f"from .tools.tool_{i} import run as tool_{i}_run" for i in range(1, tools + 1)
    )
    tool_registry = ",\n    ".join(f'"tool_{i}": tool_{i}_run' for i in range(1, tools + 1))

    (root / "src" / pkg / "server.py").write_text(
        f'''"""{safe} MCP server — generated by x4-mcpgen."""
from __future__ import annotations

import argparse
import json
import sys

{tool_imports}

TOOLS = {{
    {tool_registry},
}}

# Explicit allow-list — never use "*"
ALLOWED_TOOLS = list(TOOLS.keys())


def health() -> dict:
    return {{"status": "ok", "server": "{safe}", "tools": ALLOWED_TOOLS}}


def list_tools() -> list[dict]:
    return [{{"name": n, "description": f"Tool {{n}}"}} for n in ALLOWED_TOOLS]


def call_tool(name: str, arguments: dict | None = None) -> dict:
    if name not in TOOLS:
        return {{"error": f"tool not allowed: {{name}}", "allowed": ALLOWED_TOOLS}}
    return TOOLS[name](**(arguments or {{}}))


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="{safe}")
    p.add_argument("--health", action="store_true")
    p.add_argument("--list-tools", action="store_true")
    args = p.parse_args(argv)
    if args.health:
        print(json.dumps(health()))
        return 0
    if args.list_tools:
        print(json.dumps(list_tools(), indent=2))
        return 0
    print("{safe} MCP server — use --health or --list-tools", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
''',
        encoding="utf-8",
    )

    for i in range(1, tools + 1):
        (root / "src" / pkg / "tools" / f"tool_{i}.py").write_text(
            f'''"""Generated tool_{i}."""
from __future__ import annotations


def run(**kwargs):
    """Deterministic placeholder — replace with real logic."""
    return {{"tool": "tool_{i}", "ok": True, "input_keys": sorted(kwargs.keys())}}
''',
            encoding="utf-8",
        )
    (root / "src" / pkg / "tools" / "__init__.py").write_text("", encoding="utf-8")

    # tests
    (root / "tests" / "test_health.py").write_text(
        f'''from {pkg}.server import health, list_tools, call_tool, ALLOWED_TOOLS


def test_health():
    h = health()
    assert h["status"] == "ok"
    assert set(h["tools"]) == set(ALLOWED_TOOLS)


def test_list_tools():
    tools = list_tools()
    assert len(tools) == len(ALLOWED_TOOLS)


def test_call_allowed():
    name = ALLOWED_TOOLS[0]
    result = call_tool(name, {{}})
    assert result.get("ok") is True


def test_call_denied():
    result = call_tool("__not_a_tool__", {{}})
    assert "error" in result
''',
        encoding="utf-8",
    )

    # mcp.json — explicit tools, stdio only
    mcp = {
        "name": safe,
        "version": "0.1.0",
        "description": f"MCP server {safe} (x4-mcpgen)",
        "transports": ["stdio"],
        "tools": [{"name": f"tool_{i}"} for i in range(1, tools + 1)],
        "permissions": {
            "network": "deny",
            "filesystem": "none",
            "shell": "deny",
        },
    }
    (root / "mcp.json").write_text(json.dumps(mcp, indent=2) + "\n", encoding="utf-8")

    # schema stub
    (root / "schemas" / "tool-result.schema.json").write_text(
        json.dumps(
            {
                "$schema": "https://json-schema.org/draft/2020-12/schema",
                "type": "object",
                "required": ["ok"],
                "properties": {"ok": {"type": "boolean"}, "tool": {"type": "string"}},
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    # Dockerfile non-root
    (root / "Dockerfile").write_text(
        f"""FROM python:3.12-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -e . && useradd -m -u 10001 mcp && chown -R mcp:mcp /app
USER mcp
CMD ["python", "-m", "{pkg}.server", "--health"]
""",
        encoding="utf-8",
    )

    # SECURITY + LICENSE + CI
    (root / "SECURITY.md").write_text(
        "# Security\n\nPrivate GitHub security advisory only.\n",
        encoding="utf-8",
    )
    (root / "LICENSE").write_text(
        "Apache License 2.0 — Copyright 2026 ARIEX4Ops / dhe-cruzer69\n",
        encoding="utf-8",
    )
    (root / ".github" / "workflows" / "ci.yml").write_text(
        """name: CI
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -e ".[dev]"
      - run: ruff check .
      - run: pytest -q
""",
        encoding="utf-8",
    )

    return root
