from __future__ import annotations
from pathlib import Path

def generate_server(name: str, out: Path, tools: int = 2) -> Path:
    safe = "".join(c if c.isalnum() or c in "-_" else "-" for c in name).strip("-") or "mcp-server"
    root = out / safe
    pkg = safe.replace("-", "_")
    (root / "src" / pkg / "tools").mkdir(parents=True, exist_ok=True)
    (root / "tests").mkdir(parents=True, exist_ok=True)
    (root / "pyproject.toml").write_text(f'[project]\nname = "{safe}"\nversion = "0.1.0"\nrequires-python = ">=3.11"\n\n[build-system]\nrequires = ["setuptools>=68"]\nbuild-backend = "setuptools.build_meta"\n')
    (root / "README.md").write_text(f"# {safe}\n\nGenerated by x4-mcpgen. Not production-ready until tests/security pass.\n")
    (root / "src" / pkg / "__init__.py").write_text('__version__ = "0.1.0"\n')
    (root / "src" / pkg / "server.py").write_text('def health():\n    return {"status": "ok"}\n')
    for i in range(1, max(1, tools) + 1):
        (root / "src" / pkg / "tools" / f"tool_{i}.py").write_text(f'def run(**kw):\n    return {{"tool": {i}, "ok": True}}\n')
    (root / "tests" / "test_health.py").write_text(f'from {pkg}.server import health\ndef test_health():\n    assert health()["status"] == "ok"\n')
    (root / "mcp.json").write_text(f'{{\n  "name": "{safe}",\n  "version": "0.1.0",\n  "transports": ["stdio"]\n}}\n')
    return root
